### PR TITLE
Feature: JS 'require' recursive merge

### PR DESCRIPTION
**Pull request by mihai-stancu**

### CODE REVIEW

**Comment by matthiasmullie** [comment]
Thanks for the PR, @mihai-stancu 

Can you help me understand exactly why you'd like this?

To the best of my knowledge, require() is not standard JavaScript.
I know it exists in nodeJS. However, we probably wouldn't want to merge in nodeJS modules this way.

I'm not sure what to do with this right now. I wish there was a standard JS way to import other files.

**Comment by mihai-stancu** [comment]
I used it to write a file containing only `require` statements only to keep track of all dependencies in one file.

And I used a composer post-install / post-updade hook to run the minifier on the list of `require` statements and generate the conglomerated & minified JS file.

It's not an entirely orthodox way of using it but on the other hand I could rewrite it to be used with `requirejs` syntax which would qualify as correct in browser JS code.

**Comment by matthiasmullie** [comment]
I've also considered doing that (requirejs) in the past. I ended up not doing it for a couple of reasons:
* requirejs can pretty complex & those using it will most likely use it in a way that is too complex for the minifier to support (code relationships etc)
* if you're using requirejs to handle your dependencies etc, you may not want everything to be included in 1 giant file anyway.
* if all you need to do is combine multiple JS files in one, it can already be done from PHP (multiple `$minifier->add(...);`). If you had a file to track all your requires, you could just as easily read it in PHP.

While I'm not going to reject doing a proper requirejs implementation, I'm not sure any implementation will satisfy my first 2 concerns.

**Comment by mihai-stancu** [comment]
About 1 & 2: A RequireJS project to prod might benefit from conglomeration+minification just as much as any other project -- I'm not savvy on the field since I don't use RequireJS. OTOH RequireJS defines dependencies and after-load code execution which translate into a `requirejs` function call that couldn't (ever) be matched (correctly) by a RegEx.

About 3: Altering the code to work with very basic `requirejs` calls would be easy. Including anything else wouldn't. I'll ask a few friends working front end with requirejs to see if a naive implementation would help them at all.

**Comment by matthiasmullie** [comment]
The dependencies & after-load execution is what I was talking about. I think those are the biggest reasons to use `requirejs`, and then devs have probably carefully crafted what should load exactly when.
Plus in those cases, it's indeed too complex to include that in minifier.

If you can make very basic `requirejs` support work - only for those intended to be loaded immediately and only once, so we can safely include the content - that would be nice.

**Comment by mihai-stancu** [comment]
I hope I'll get the chance to do it this weekend and finish this PR.

**Comment by mihai-stancu** [comment]
The RegEx I made doesn't correlate the parameter type (`array`) for requirejs, meaning that you could for example use any of the following:

* `require('file.js'); //valid`
* `requirejs(['file.js']); //valid`
* `require(['file.js']); //invalid`
* `requirejs('file.js'); //invalid`

**Comment by matthiasmullie** [comment]
Woah, I hadn't seen the update to this PR. I'll try to check this out this week!

**Comment by mihai-stancu** [comment]
Bump.

**Comment by mihai-stancu** [comment]
Bump

**Comment by matthiasmullie** [comment]
The current pull request assumes the `.js` suffix is part of the `require`.
Judging from RequireJS's website, common usage seems to look like this:
```js
require("module/name")
```
which then includes: `modules/name.js`.

An additional concern is how it is decided what path the `require`s are relative to (as configured in `requirejs.config`)

In it's current state, at least the discrepancy of `.js` seems a serious blocker. I may have to get a little more comfortable with RequireJS & create some tests we'd need to pass before considering this feature.

**Comment by mihai-stancu** [comment]
The feature isn't all that useful for RequireJS users, the regex doesn't cover multi-require and multiple parameters, it requires parsing config files to do the job.

You're right, this whole thing is half-baked on my part. I'll close the PR and maybe I'll give it another go after I've used RequireJS and if I feel it would be useful.

**Pull request closed without merging**
