### PR TITLE
Commented "get rid of double semicolons" code

### PR DESCRIPTION
**Pull request by r4nm4**
I need the double ;; because in some case I have an issue

### CODE REVIEW

**Comment by r4nm4** [comment]
I'm really sorry, I didn't want to committed something in matthiasmullie:master :(

**Comment by matthiasmullie** [comment]
Don't worry! All you did was create a pull request - it wasn't in matthiasmullie:master yet! (GitHub wouldn't allow that unless you have the proper permissions anyway) It was still up to me to decide to merge it into matthiasmullie:master or not.

Can you let me know why you don't want multiple semicolons to be collapsed into 1? Do you have an example where it's not ok to do that? I'm definitely open to improving that code if it has unintended side-effects!

**Comment by r4nm4** [comment]
Thanks! Sure, I had this issue with "jquery-ui.min.js" v1.10.3
Btw... this "library" is amazing! Much better then other!

**Comment by matthiasmullie** [comment]
Alright thanks! I've pushed a fix & will release a new version tomorrow!

**Comment by r4nm4** [comment]
Awesome! Well done! :)

**Pull request closed without merging**
