### PR TITLE
Fix #317 handling of preserved comments in CSS

### LINKED ISSUE #317: CSS minification logic for @license and @preserve is wrong, and sometimes very slow
This regexp is both wrong, and can be very, very slow on large input.

```
'/\n?\/\*(!|.*?@license|.*?@preserve).*?\*\/\n?/s'
```

https://github.com/matthiasmullie/minify/blob/master/src/CSS.php#L639

The error is that the .*? before the @licence will match anything, including */. Therefore, if your CSS contains:

```CSS
/* First comment */
.lots .of .css .rules {}

/* @preserve */
```

Then all the .lots .of .css .rules {} don't get minified.

Also, in the context of Moodle (https://moodle.org/), this regexp (which was being matched only 2 times) was taking 15 seconds to do that!

I have found a way to improve it (time down to a fraction of a second, and all input minified). Pull request coming shortly.

### PR DESCRIPTION
**Pull request by timhunt**
I hope this is OK. It is my first pull request here.

Your CONTRIBUTING.md was very clear (thanks!) but I may still have missed something. If so, sorry, please let me know, and I will be happy to fix.

### CODE REVIEW

**Comment by timhunt** [comment]
Thanks to scrutinizer for poniting out that this applies to JS too. Amended fix coming up.

**Comment by timhunt** [comment]
Sorry, I don't understand whay appveyor is trying to do, and I can't work out what the logs mean. If I need to fix something, please explain.

I felt it was clearer to leave the change as two separate commits, but if you disagree, let me know what you would like instead.

This fix may explain a number of the open issues about chunks of files not getting minimised.

**Comment by davidscotson** [comment]
Issues #288, #283, #294 and #310 seem like they might be fixed by this PR.

**Comment by timhunt** [comment]
I was just wondering if we could get this fix landed? If you are waiting for me to do something, then please help me to understand what needs to be done. Thank you.

**Pull request merged**
