### PR TITLE
Allow URL-rewriting without saving the minified content to the file system

### PR DESCRIPTION
**Pull request by throup**
Fixes issue #61

### CODE REVIEW

**Comment by matthiasmullie** [comment]
Thanks for the pull request, @throup

If `$save` is set to false, it does exactly the same as `execute()` already does. What do you think about just making that one public instead of protected? Then we don't need that additional param & conditional in `minify()`

**Comment by throup** [comment]
That would work for my needs, @matthiasmullie. The one advantage I could see for the parameter would be to allow applications to pass it in from their own config. But I would be happy to use either solution.

**Comment by matthiasmullie** [comment]
Yeah, it would make it slightly easier for applications to immediately set it from config, but they still can. They just need to wrap an if/else around it themselves. I feel like the application is the correct place for such config switches, not libraries :)

Any chance you could update your PR to just make `execute()` public? I'll merge it right away then.

**Comment by throup** [comment]
No problem, Matthias. I've updated the PR; ready for merging.

**Comment by matthiasmullie** [comment]
Perfect, thanks!

**Pull request merged**
